# Generated by Django 4.0.3 on 2022-04-02 20:35

from django.db import migrations, models
import django.db.models.deletion
import module_main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('documentId', models.AutoField(primary_key=True, serialize=False)),
                ('documentName', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
                ('rules', models.JSONField(default=module_main.models.rol_for_default)),
                ('numDoc', models.CharField(max_length=20, unique=True)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('dateBirth', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('credit', models.CharField(max_length=20)),
                ('dateRegister', models.DateField(default=module_main.models.get_date_current)),
                ('active', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('deliveryId', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryName', models.CharField(max_length=50)),
                ('document', models.CharField(max_length=20, unique=True)),
                ('dateBirth', models.DateField()),
                ('phoneNumber', models.CharField(max_length=12, unique=True)),
                ('active', models.CharField(default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('documentId', models.AutoField(primary_key=True, serialize=False)),
                ('documentName', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoce',
            fields=[
                ('invoceId', models.AutoField(primary_key=True, serialize=False)),
                ('priceAll', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=module_main.models.get_date_current)),
                ('priceDistribution', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodId', models.AutoField(primary_key=True, serialize=False)),
                ('prodName', models.CharField(max_length=50)),
                ('nameImg', models.FileField(max_length=400, upload_to='Products')),
                ('description', models.CharField(max_length=300)),
                ('mark', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valued', models.IntegerField()),
                ('warranty', models.IntegerField()),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_main.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderBy', models.AutoField(primary_key=True, serialize=False)),
                ('deliverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_main.delivery')),
                ('invoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_main.invoce')),
            ],
        ),
        migrations.AddField(
            model_name='invoce',
            name='prodContent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='module_main.product'),
        ),
        migrations.AddField(
            model_name='invoce',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_main.client'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='typeDoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_main.document'),
        ),
        migrations.AddField(
            model_name='client',
            name='typeDoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_main.document'),
        ),
    ]
