# Generated by Django 4.0.3 on 2022-04-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='active',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='valued',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(default=0),
        ),
    ]
