# Generated by Django 4.0.3 on 2022-04-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_main', '0002_alter_client_active_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nameImg',
            field=models.FileField(max_length=400, upload_to='Images/'),
        ),
    ]
