# Generated by Django 4.0.3 on 2022-04-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_main', '0003_alter_product_nameimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='documentId',
            new_name='categoriesId',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='documentName',
            new_name='categoriesName',
        ),
    ]
