# Generated by Django 4.0.3 on 2022-04-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_main', '0004_rename_documentid_categorie_categoriesid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='categoriesId',
            new_name='categorieId',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='categoriesName',
            new_name='categorieName',
        ),
    ]
