# Generated by Django 4.0.3 on 2022-04-03 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_main', '0005_rename_categoriesid_categorie_categorieid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='credit',
            new_name='debitCard',
        ),
    ]
