# Generated by Django 4.0.3 on 2022-04-03 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_main', '0006_rename_credit_client_debitcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderBy',
            new_name='orderId',
        ),
    ]
