# Generated by Django 4.0.3 on 2022-04-03 04:03

from django.db import migrations, models
import module_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('module_main', '0008_order_date_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nameImg',
            field=models.FileField(max_length=400, upload_to='', validators=[module_main.models.valid_extension]),
        ),
    ]
