# Generated by Django 4.0.3 on 2022-04-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_main', '0012_alter_categorie_categoriename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='categorieId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
