# Generated by Django 4.0.3 on 2022-04-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_main', '0013_alter_categorie_categorieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='categorieId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='categorieName',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='documentName',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
